#Projetos de apoio 

github: # Raqui vao os usernames dos patrocinadores     
patreon: # patreon do projeto 
community_bridge: # links de projetos de comunidades 
custom: # link s de comunidades parceiras   
