#Projetos de apoio 

github: https://github.com/abel8260/subs---sigdu-kingdom   
gateway: # patreon do projeto 
community_bridge: https://github.com/abel8260/subs---sigdu-kingdom/discussions
custom: https://abel8260.itch.io/reinos-de-sigdu   
