#Projetos de apoio 

github: # Raqui vao os usernames dos patrocinadores     
patreon: # patreon do projeto 
community_bridge: https://github.com/abel8260/subs---sigdu-kingdom/discussions
custom: # link s de comunidades parceiras   
